import random

"""
In this project, the user tries to guess a number that the computer has generated.

A random number is generated by using the randint function.

Then, using a series of prompts, the user guesses integers until they reach the
number that was generated by the computer. If they guess too high, they are
prompted with a message indicating so. If they guess too low, they are prompted
with a message indicating so.
"""

def guess_number(x):
    random_number = random.randint(1, x)
    guess = 0
    while guess != random_number:
        guess = int(input(f"Guess a number between 1 and {x}: "))
        if guess < random_number:
            print("Sorry, guess again. Too low.")
        elif guess > random_number:
            print("Sorry, guess again. Too high.")
    print(f"Yay! You have guessed the number {random_number}!")
